LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := nfcstackp
LOCAL_SRC_FILES := nfcstackp
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_MULTILIB := 32
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)
