LOCAL_PATH := $(call my-dir)

include $(LOCAL_PATH)/PL.mk
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_UNSTRIPPED_PATH := $(TARGET_ROOT_OUT_SBIN_UNSTRIPPED)
LOCAL_MULTILIB := 32
include $(BUILD_EXECUTABLE)


include $(LOCAL_PATH)/halimpl.mk
LOCAL_MODULE_RELATIVE_PATH := hw
include $(BUILD_SHARED_LIBRARY)
